packages:
  - "packages/*"

overrides:
  chokidar: "^5.0.0"
  esbuild: "^0.28.1"
  eslint: "^10.6.0"
  js-yaml: "^3.15.0"
  lodash-es: "^4.18.1"
  react: "^19.2.7"
  uuid: "^14.0.0"
  yaml: "^2.9.0"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@moonrepo/cli@2.3.5 || 2.4.2'
  - '@moonrepo/core-linux-arm64-gnu@2.3.5 || 2.4.2'
  - '@moonrepo/core-linux-arm64-musl@2.3.5 || 2.4.2'
  - '@moonrepo/core-linux-x64-gnu@2.3.5 || 2.4.2'
  - '@moonrepo/core-linux-x64-musl@2.3.5 || 2.4.2'
  - '@moonrepo/core-macos-arm64@2.3.5 || 2.4.2'
  - '@moonrepo/core-macos-x64@2.3.5 || 2.4.2'
  - '@moonrepo/core-windows-x64-msvc@2.3.5 || 2.4.2'
  - '@storybook/builder-vite@10.5.0'
  - '@storybook/csf-plugin@10.5.0'
  - '@storybook/react-dom-shim@10.5.0'
  - '@storybook/react-vite@10.5.0'
  - '@storybook/react@10.5.0'
  - storybook@10.5.0
