#!/usr/bin/env node
// Assembles a single static site for Netlify:
//   /                -> renderer-showcase (static)
//   /apps/<name>/    -> each framework app (static SPA / static)
//   /apps/react/*    -> app-react client assets (static); its HTML is server-rendered
//                       by the Netlify function bundled from netlify/functions-src/
import { execFileSync } from 'node:child_process';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build as esbuild } from 'esbuild';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const publishDir = join(root, 'dist-site');

// package dir -> URL segment under /apps/
const STATIC_APPS = [
  ['app-preact', 'preact'],
  ['app-vue', 'vue'],
  ['app-svelte', 'svelte'],
  ['app-solidjs', 'solidjs']
];

function run(cmd, args, extraEnv) {
  console.log(`\n$ ${cmd} ${args.join(' ')}`);
  execFileSync(cmd, args, {
    cwd: root,
    stdio: 'inherit',
    env: extraEnv ? { ...process.env, ...extraEnv } : process.env
  });
}

// 1. Build every workspace package (libs + apps + showcase) in dependency order.
run('pnpm', ['exec', 'moon', 'run', ':build']);

// 2. Rebuild each static SPA with its subpath as the public base.
for (const [dir, name] of STATIC_APPS) {
  run('pnpm', ['--dir', `packages/${dir}`, 'exec', 'vite', 'build', `--base=/apps/${name}/`]);
}

// 3. Astro (static) under /apps/astro/.
run('pnpm', ['--dir', 'packages/app-astro', 'exec', 'astro', 'build'], { SITE_BASE: '/apps/astro/' });

// 4. app-react client bundle under /apps/react/client/ (hydrates the SSR HTML from the function).
run('pnpm', [
  '--dir',
  'packages/app-react',
  'exec',
  'vite',
  'build',
  '--config',
  'vite.client.config.ts',
  '--base=/apps/react/client/'
]);

// 5. Assemble the combined publish directory.
await rm(publishDir, { recursive: true, force: true });
await mkdir(publishDir, { recursive: true });

// renderer-showcase at the root
await cp(join(root, 'packages/renderer-showcase/dist'), publishDir, { recursive: true });

// root favicon so browsers' implicit /favicon.ico request resolves across the whole site
await cp(join(root, 'public/favicon.ico'), join(publishDir, 'favicon.ico'));

// static apps + astro at /apps/<name>/
for (const [dir, name] of [...STATIC_APPS, ['app-astro', 'astro']]) {
  await cp(join(root, `packages/${dir}/dist`), join(publishDir, 'apps', name), { recursive: true });
}

// app-react static client assets at /apps/react/client/ (SSR HTML comes from the Netlify function)
await cp(
  join(root, 'packages/app-react/dist/client'),
  join(publishDir, 'apps', 'react', 'client'),
  { recursive: true }
);

// 6. Emit the resolved app-react client assets for the Netlify function to import.
const manifestPath = join(root, 'packages/app-react/dist/client/.vite/manifest.json');
let assets = { js: '/apps/react/client/entry-hydration.js', css: [] };
if (existsSync(manifestPath)) {
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  const entry = manifest['src/entry-hydration.tsx'];
  if (entry) {
    assets = {
      js: `/apps/react/client/${entry.file}`,
      css: (entry.css ?? []).map((c) => `/apps/react/client/${c}`)
    };
  }
}
await writeFile(
  join(root, 'netlify/functions-src/app-react-assets.mjs'),
  `// Generated by scripts/build-site.mjs — resolved app-react client assets for SSR.\nexport default ${JSON.stringify(assets, null, 2)};\n`
);

// 7. Pre-bundle the SSR function into a single self-contained file. Netlify's own
// bundler does not follow pnpm workspace symlinks (it left @cheshirecode/hono-base as a
// bare runtime import -> 502), so we inline everything here. The createRequire banner
// lets react-dom/server's CommonJS `require('util')` work in the ESM output.
await mkdir(join(root, 'netlify/functions'), { recursive: true });
await esbuild({
  entryPoints: [join(root, 'netlify/functions-src/app-react.mts')],
  outfile: join(root, 'netlify/functions/app-react.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  define: { 'process.env.NODE_ENV': '"production"' },
  banner: { js: 'import { createRequire as ___cr } from "module"; const require = ___cr(import.meta.url);' },
  logLevel: 'warning'
});

console.log(`\nSite assembled at ${publishDir}`);
