name: build snapshot

on:
  push:
  pull_request:
jobs:
  base:
    uses: ./.github/workflows/base.yml
    with:
      build: false
      lcov: false
      storybook: false
  app-1:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: app-1
      storybook: true
      lcov: true
  eslint-config-react:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: eslint-config-react
      namespace: '@fieryeagle'
      lcov: true
  browser-clipboard:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: browser-clipboard
      namespace: '@fieryeagle'
      lcov: true
  measure-hook:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: measure-hook
      lcov: true
      build: false
  pkce:
    needs: [base]
    uses: ./.github/workflows/base.yml
    with:
      package-name: pkce
      namespace: '@fieryeagle'
      lcov: true
  finish:
    needs: [app-1,eslint-config-react,browser-clipboard,measure-hook,pkce]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "app-1,eslint-config-react,browser-clipboard,measure-hook,pkce"
